import { gql } from '@apollo/client';
export const ProductDetailsFragment = gql`
    fragment ProductDetailsFragment on ProductInterface {
        __typename
        review_count
        rating_summary
        group_product_url
        redirect
        stock_status
        size_attribute
        design_attribute
        callForPrice
        special_price
        group_product_sum
        delivery
        warranty
        seoJson
        newpArrival
        created_at
        ... on SimpleProduct {
            price_range{
                minimum_price
                {
                    discount
                    {
                        percent_off
                        amount_off
                    }
                    final_price
                    {
                        value
                        currency
                    }
                    fixed_product_taxes{
                        label
                        amount
                        {
                            currency
                            value
                        }
                    }
                }
                maximum_price
                {
                    discount
                    {
                        percent_off
                        amount_off
                    }
                    final_price
                    {
                        value
                        currency
                    }
                    fixed_product_taxes{
                        label
                        amount
                        {
                            currency
                            value
                        }
                    }
                }
            }
        }
        reviews{
            items{
                nickname
                average_rating
                summary
                text
                created_at
                ratings_breakdown{
                    name
                    value
                }
            }
        }
        categories {
            id
            name
            breadcrumbs {
                category_id
            }
        }
        description {
            html
        }
        id
        media_gallery_entries {
            id
            label
            position
            disabled
            file
            video_content{
                media_type
                video_provider
                video_url
                video_title
                video_description
                video_metadata
            }
        }
        meta_description
        meta_title
        name
        emi
        price {
            regularPrice {
                amount {
                    currency
                    value
                }
            }
        }
        sku
        callForPrice
        group_product_id
        custom_label
        other_labels
        small_image {
            label
            url
        }
        url_key
        ... on ConfigurableProduct {
            configurable_options {
                attribute_code
                attribute_id
                id
                label
                values {
                    default_label
                    label
                    store_label
                    use_default_value
                    value_index
                    swatch_data {
                        ... on ImageSwatchData {
                            thumbnail
                        }
                        value
                    }
                }
            }
            price_range{
                minimum_price
                {
                    discount
                    {
                        percent_off
                        amount_off
                    }
                    final_price
                    {
                        value
                        currency
                    }
                    fixed_product_taxes{
                        label
                        amount
                        {
                            currency
                            value
                        }
                    }
                }
                maximum_price
                {
                    discount
                    {
                        percent_off
                        amount_off
                    }
                    final_price
                    {
                        value
                        currency
                    }
                    fixed_product_taxes{
                        label
                        amount
                        {
                            currency
                            value
                        }
                    }
                }
            }
            variants {
                attributes {
                    code
                    value_index
                }
                product {
                    id
                    media_gallery_entries {
                        id
                        disabled
                        file
                        label
                        position
                        video_content{
                            media_type
                            video_provider
                            video_url
                            video_title
                            video_description
                            video_metadata
                        }
                    }
                    sku
                    stock_status
                    price {
                        regularPrice {
                            amount {
                                currency
                                value
                            }
                        }
                    }
                   
                }
            }
        }
        ...on BundleProduct {
            dynamic_sku
            dynamic_price
            dynamic_weight
            price_view
            price_range{
                minimum_price
                {
                    discount
                    {
                        percent_off
                        amount_off
                    }
                    final_price
                    {
                        value
                        currency
                    }
                    fixed_product_taxes{
                        label
                        amount
                        {
                            currency
                            value
                        }
                    }
                }
                maximum_price
                {
                    discount
                    {
                        percent_off
                        amount_off
                    }
                    final_price
                    {
                        value
                        currency
                    }
                    fixed_product_taxes{
                        label
                        amount
                        {
                            currency
                            value
                        }
                    }
                }
            }
            ship_bundle_items
            items {
                uid
                title
                required
                type
                position
                sku
                options {
                    uid
                    quantity
                    position
                    is_default
                    price
                    price_type
                    can_change_quantity
                    label
                    product {
                        uid
                        name
                        sku
                        stock_status
                        url_key
                        url_suffix
                        price {
                            regularPrice {
                                amount {
                                    currency
                                    value
                                }
                            }
                        }
                        price_range{
                          minimum_price
                          {
                            discount
                            {
                              percent_off
                              amount_off
                            }
                            final_price
                            {
                              value
                              currency
                            }
                            fixed_product_taxes{
                              label
                              amount
                            {
                              currency
                              value
                            }
                            }
                          }
                          maximum_price
                         {
                            discount
                            {
                              percent_off
                              amount_off
                            }
                            final_price
                            {
                              value
                              currency
                            }
                            fixed_product_taxes{
                              label
                              amount
                            {
                              currency
                              value
                            }
                            }
                          }
                        }
                        small_image {
                            url
                            label
                        }
                        __typename
                    }
                }
            }
        }
        ... on GroupedProduct {
            items{
                qty
                position
                product{
                    id
                    sku
                    name
                    stock_status
                    url_key
                    url_suffix
                    __typename
                    url_key
                    small_image {
                        url
                        label
                    }
                    price{
                        regularPrice{
                            amount{
                                currency
                                value
                            }
                        }
                    }
                    price_range{
                        minimum_price
                        {
                          discount
                          {
                            percent_off
                            amount_off
                          }
                          final_price
                          {
                            value
                            currency
                          }
                          fixed_product_taxes{
                            label
                            amount
                          {
                            currency
                            value
                          }
                          }
                        }
                        maximum_price
                       {
                          discount
                          {
                            percent_off
                            amount_off
                          }
                          final_price
                          {
                            value
                            currency
                          }
                          fixed_product_taxes{
                            label
                            amount
                          {
                            currency
                            value
                          }
                          }
                        }
                      }
                }
            }
        }
    }
`;
